version: "3"

services:
  postgres-dashboard-v3:
    container_name: postgres-dashboard-v3
    image: postgres:12
    env_file:
      - ./.docker.env
    ports:
    - 5432:5432
    networks:
      - dashboard-v3

networks:
  dashboard-v3: